# Generated by Django 2.2.3 on 2019-08-08 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('LibID', models.CharField(max_length=25)),
                ('UID', models.CharField(max_length=25)),
                ('RollNo', models.CharField(max_length=25)),
                ('UniRollNo', models.CharField(max_length=25)),
                ('Mobile_no', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=100)),
                ('linkB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Directory.Bran')),
            ],
        ),
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=100)),
                ('linkC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Directory.Semes')),
            ],
        ),
        migrations.AddField(
            model_name='bran',
            name='linkA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Directory.Cou'),
        ),
    ]
