# Generated by Django 2.2.3 on 2019-08-18 17:17

import Directory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0002_auto_20190818_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDropdown',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False, verbose_name=Directory.models.StudentCourseDetail)),
                ('pid', models.IntegerField(blank=True, db_column='Pid', null=True)),
                ('field', models.CharField(blank=True, db_column='Field', max_length=500, null=True)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=500, null=True)),
                ('is_delete', models.IntegerField(db_column='Is_Delete')),
                ('is_edit', models.IntegerField(db_column='Is_Edit')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee_dropdown',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DirectoryBran',
        ),
        migrations.DeleteModel(
            name='DirectoryCou',
        ),
        migrations.DeleteModel(
            name='DirectoryDetails',
        ),
        migrations.DeleteModel(
            name='DirectorySec',
        ),
        migrations.DeleteModel(
            name='DirectorySemes',
        ),
    ]
